Finish tests

diff --git a/bin/tests b/bin/tests
--- a/bin/tests
+++ b/bin/tests
@@ -4,20 +4,33 @@ set -e
 
 function usage() {
   cat <<USAGE >&2
-Usage: tests [-h] [/path/to/test]
+Usage: tests [-h] [-e ENV1,ENV2,...] [/path/to/test]
+
+  -e  Environments to test(s)
   -h  Show help
+
 USAGE
   exit ${1:--1}
 }
 
 
-# check if stdout is a terminal...
+# Run clean up actions on process exit
+function on_exit() {
+  if [[ -d "$outputdir" ]]; then
+    rm -rf "$outputdir"
+  fi
+}
+
+trap on_exit EXIT
+
+
+# Set up environment variable for colorizing output
 function setup_colors() {
-  if test -t 1; then
-
-    # see if it supports colors...
+  # For checking if STDOUT is a terminal, use:
+  # if test -t 1; then
+  if true ; then
+    # See if it supports colors
     ncolors=$(tput colors)
-
     if test -n "$ncolors" && test $ncolors -ge 8; then
       bold="$(tput bold)"
       underline="$(tput smul)"
@@ -37,14 +50,19 @@ function setup_colors() {
 
 
 readonly compose=docker/tests.yml
+readonly outputdir=$(mktemp --tmpdir -d dockertest.XXXXX)
 
 
 # Build images ($@)
 function build_images() {
   declare -a services=("${@}")
-  docker-compose -f $compose build \
-                 --force-rm \
-                 "${services[@]}"
+  docker-compose -f $compose build --force-rm "${services[@]}"
+}
+
+
+# Run tests in a container
+function run_container() {
+  docker-compose -f $compose up --abort-on-container-exit
 }
 
 
@@ -52,38 +70,42 @@ function build_images() {
 # tests are run
 function run_tests() {
   export TESTPATH=$1
-  export PYVERS="py27 py37"
-
-  local pids=""
+  local environs=(${2//,/ })
   declare -A pmap
-  
-  for PYVER in $PYVERS ; do
-    export PYVER
-    export COMPOSE_PROJECT_NAME=$PYVER
-    ( build_images mime_streamer_test >> tmp/$PYVER 2>&1 && \
-        docker-compose -f $compose up --abort-on-container-exit >> tmp/$PYVER 2>&1 ) &
-    local pid="$!"
-    pmap["$pid"]=$PYVER
-    pids+=" $pid"
-  done
 
   setup_colors
-  
-  for pid in $pids ; do
-    local PYVER=${pmap[$pid]}
-    
+
+  for environ in "${environs[@]}" ; do
+    echo "${cyan}${environ}:${normal} Starting..." >&2
+
+    local outfile="$outputdir/$environ"
+
+    export PYVER=$environ
+    export COMPOSE_PROJECT_NAME=$environ
+    ( build_images mime_streamer_test > $outfile 2>&1 \
+        && run_container >> $outfile 2>&1 ) &
+
+    local pid="$!"
+    pmap["$pid"]=$environ
+  done
+
+  for pid in "${!pmap[@]}" ; do
+    local environ=${pmap[$pid]}
     if wait $pid ; then
-      echo "Success $PYVER"
+      echo "${cyan}${environ}:${normal} ${blue}Success${normal}" >&2
     else
-      cat tmp/$PYVER
-      echo "${red}Fail ${PYVER}${normal}"
+      cat $outputdir/$environ | sed -e 's/^/'"${cyan}${environ}:${normal}"' /'
+      echo "${cyan}${environ}:${normal} ${red}Failed${normal}" >&2
     fi
   done
 }
 
 
-while getopts "h" opt; do
+while getopts "e:h" opt; do
   case $opt in
+    e)
+      envs=$OPTARG
+      ;;
     h)
       usage 0
       ;;
@@ -98,5 +120,7 @@ while getopts "h" opt; do
 done
 shift $(($OPTIND - 1))
 
+readonly testpath=${1:-tests/}
+readonly envs=${envs:-py27,py37}
 
-run_tests "${1:-tests/}"
+run_tests "$testpath" "$envs"
